---
title: "TDM"
author: "Chris HJ Hartgerink"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: pdf_document
---

<!--- A submission for LIBER journal
https://www.liberquarterly.eu/about/submissions/ 

Markdown citations:

pandoc -s -S --bibliography biblio.bib --filter pandoc-citeproc CITATIONS -o example24a.html

pandoc -s -S --bibliography biblio.json --filter pandoc-citeproc --csl chicago-fullnote-bibliography.csl CITATIONS -o example24b.html

pandoc -s -S --bibliography biblio.yaml --filter pandoc-citeproc --csl ieee.csl CITATIONS -t man -o example24c.1

---->

<!--- 
Case studies present in depth studies of particular situations in an illustrative way, without restricting themselves to a single research procedure. A case study records the practices of the profession by narrowing down a very broad field of research into one, real-world topic and providing factual evidence and revealing facts or information otherwise ignored or unknown. While critical judgment and organization of the material are required, generally, writers should stick to the facts by providing a fairly modest and honest record of the events. With a short introduction, a case study should provide an explanation, why is the given case particularly interesting. The case study has to contain the most important information obtained about it, followed by a plan for analysing the problem at hand and the options to solve it. 
--->

The vast amount of scientific literature is ripe for the pickings; information can be mined from text- and data in previous research articles in order to create new knowledge. This methodology, Text- and Data Mining (TDM), contains many fruitful possibilities, including an automated hypothesis finder [@malhotra2013], semi-automated meta-analysis procedures [], statistical error detection [], and in my case, detecting potential data fabrication in the sciences. TDM offers many possibilities, but researchers wanting to apply these methods face grave problems ahead. 

The researchers wanting to apply TDM methods will have to face navigating the publisher's landscape and copyright's landscape.

This case study focuses on my personal experiences while Text- and Data Mining, incorporating a

# Copyright
## Copyright landscape
## Copyright exception

# TDM
## Format
HTML PDF XML txt

# Elsevier
## Block
## API
## Lega

